/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Learn-in-depth
//Mahmoud 3id
//Mastering_Embedded System online diploma
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
//#include"Stm32f103x8.h"
#include "Stm32f103x8.h"
#include "Stm32f103x8_EXTI_drivers.h"
#include "Stm32f103x8_gpio_drivers.h"
#include "Stm32f103x8_USART_drivers.h"
#include "Stm32f103x8_SPI_drivers.h"
#include "Lcd.h"
#include "Keypad.h"
volatile unsigned int var6;
extern unsigned int _estack;

#define main_stack_size   512
#define Task_A_stack_size   100
#define Task_B_stack_size   100

/*Bonders of Main Stack Pointer (MSP)*/
unsigned int S_MSP =(unsigned int)&_estack;
unsigned int E_MSP;


/*Bonders of Process Stack Pointer of TaskA (PSP_TA)*/
unsigned int S_PSP_TaskA;
unsigned int E_PSP_TaskA;


/*Bonders of Process Stack Pointer of TaskB (PSP_TB)*/
unsigned int S_PSP_TaskB;
unsigned int E_PSP_TaskB;

uint8_t IRQ_Flag = 0;
uint8_t TaskA_Flag = 0;
uint8_t TaskB_Flag = 0;

////"MOV R1, #0x02 \n\t"
#define OS_Set_PSP_Val(address)      __asm volatile ("mov R0,%[IN] \n\t" "MSR PSP, R0": :[IN] "r"(address))

#define OS_Set_SP_shadowto_PSP       __asm volatile ("MRS R0,CONTROL \n\t" "ORR R0,R0,#0x2 \n\t" "MSR CONTROL, R0")

#define OS_Set_SP_shadowto_MSP     __asm volatile ("MRS R0,CONTROL \n\t" "AND R0,R0,#0x5 \n\t" "MSR CONTROL, R0")

#define OS_Switch_Privileged_to_Unprivileged  __asm volatile ("MRS R0,CONTROL \n\t" "ORR R0,R0,#0x1 \n\t" "MSR CONTROL, R0")


#define OS_Switch_Unprivileged_to_Privileged   __asm volatile ("MRS R0,CONTROL \n\t" "AND R0,R0,#0x6 \n\t" "MSR CONTROL, R0")

#define OS_Generate_Exception_Inerrupt					__asm("SVC #0x3")


int TaskA_Fun(int a, int b, int c)
{
	return a+b+c;
}

int TaskB_Fun(int a, int b, int c, int d)
{
	return a+b+c+d;
}

void SVC_Handler(void)
{
	OS_Switch_Unprivileged_to_Privileged;
}



void Clock_Init()
{
	//open clock of AFIO
	RCC_AFIO_CLK_EN();
	//open clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//open clock of GPIOB
	RCC_GPIOB_CLK_EN();
}


void GPIO_Init()
{
	     GPIO_Pinconfige_t pin_config ;

		//PA1: (Mode >> Input mode(00)) (CNF >>  Floating input(01))
		pin_config.Pin_Number = GPIO_PIN_1;
		pin_config.Mode = GPIO_MODE_INPUT_FLO;
		GPIOx_init(GPIOA, &pin_config);

		//PA13: (Mode >> Input mode(00)) (CNF >>  Floating input(01))
		pin_config.Pin_Number = GPIO_PIN_13;
		pin_config.Mode = GPIO_MODE_INPUT_FLO;
		GPIOx_init(GPIOA, &pin_config);

		//PB1: (Mode >> Output mode, max speed 10 MHz(01)) (CNF >> General purpose output push-pull(00))

		pin_config.Pin_Number = GPIO_PIN_1;
		pin_config.Mode = GPIO_MODE_OUTPUT_PP;
		pin_config.Speed = GPIO_MODE_speed_10_MHz;
		GPIOx_init(GPIOB, &pin_config);

		//Pin13: (Mode >> Output mode, max speed 10 MHz(01)) (CNF >> General purpose output push-pull(00))
		pin_config.Pin_Number = GPIO_PIN_13;
		pin_config.Mode = GPIO_MODE_OUTPUT_PP;
		pin_config.Speed = GPIO_MODE_speed_10_MHz;
		GPIOx_init(GPIOB, &pin_config);
}
void __delay__(uint32_t x)
{
	uint32_t i, j;

	for(i = 0; i < x; i++)
		for(j = 0; j < 255; j++);
}

void NMI_Handler(){

}
void HardFault_Handler(){

}
void MemManage_Handler(){

}
void BusFault_Handler(){

}

enum CPU_ACCESS_LEVEL
{
	privileged,
	unprivileged
};

void SWITCH_CPU_ACCESS_LEVEL (enum CPU_ACCESS_LEVEL ACCESS_LEVEL){
	switch(ACCESS_LEVEL){
	case privileged:
		__asm("MRS R0,CONTROL\n\t"
		       "LSR R0,R0,#1 \n\t"
			   "LSL R0,R0,#1 \n\t"
			   "MSR CONTROL,R0\n\t");
		break;
	case unprivileged:
		__asm("MRS R0,CONTROL\n\t"
				"ORR R0,R0,#1 \n\t"
				"MSR CONTROL,R0\n\t");
		break;
	}
}
void INT_ACTION(void)
{
	/*__asm("mrs %[out1],IPSR"
	    		:[out1] "=r"(var6));
	SWITCH_CPU_ACCESS_LEVEL(privileged);
	GPIOx_TOGGELE_PIN(GPIOB, GPIO_PIN_13);*/

	if(IRQ_Flag == 0)
	{
		TaskA_Flag = 1;
		IRQ_Flag = 1;
	}
	else if(IRQ_Flag == 1)
	{
		TaskB_Flag = 1;
		IRQ_Flag = 0;
	}
	else
	{

	}
}


void main_os(){

	/* OS Stack */
	E_MSP=(S_MSP-main_stack_size);

	/* TaskA Stack */
	S_PSP_TaskA = (E_MSP-8);

	E_PSP_TaskA =(S_PSP_TaskA-Task_A_stack_size);


	/* TaskB Stack */
	S_PSP_TaskB = (E_PSP_TaskA-8);

	E_PSP_TaskB =(S_PSP_TaskB-Task_B_stack_size);




	while(1){

		__asm("NOP");

		if(TaskA_Flag == 1)
		{
			/* Set PSP with _S_PSP_TaskA */
			OS_Set_PSP_Val(S_PSP_TaskA);

			/* Set SP --> PSP not MSP */
			OS_Set_SP_shadowto_PSP;

			/* Switch from privileged --> unprivileged*/
			OS_Switch_Privileged_to_Unprivileged;

			/* Call TaskA */
			TaskA_Flag = TaskA_Fun(1, 2, 3);

			/* Switch from unprivileged --> privileged*/
			OS_Generate_Exception_Inerrupt;

			/* Set SP --> MSP not PSP */
			OS_Set_SP_shadowto_MSP;
		}else if(TaskB_Flag == 1)
		{
			/* Set PSP with _S_PSP_TaskB */
			OS_Set_PSP_Val(S_PSP_TaskB);

			/* Set SP --> PSP not MSP */
			OS_Set_SP_shadowto_PSP;

			/* Switch from privileged --> unprivileged*/
			OS_Switch_Privileged_to_Unprivileged;

			/* Call TaskB */
			TaskB_Flag = TaskB_Fun(1, 2, 3, 4);

			/* Switch from unprivileged --> privileged*/
			OS_Generate_Exception_Inerrupt;

			/* Set SP --> MSP not PSP */
			OS_Set_SP_shadowto_MSP;
		}
		else
		{

		}
	}

}


EXTI_Configer_t EXTI_CONGIG;

int main(void)
{

	Clock_Init();

	GPIO_Init();

    __asm("nop\n\t"
    		"nop\n\t"
    		"nop\n\t");

    volatile unsigned char var1,var2=5,var3=4,sum;
    __asm("MOV %[out1],#0xFF"
    		:[out1] "=r"(var1));


    __asm("mov R0,%[IN0]"
    		:
    		:[IN0] "r"(var1));
    __asm("add %[OUT0],%[IN0],%[IN1]"
        		:[OUT0] "=r" (sum)
        		:[IN0] "r"(var2),
				 [IN1] "r"(var3)
				:"r2","r3");
    __asm("mrs %[out0],CONTROL"
    		:[out0] "=r"(var1));

    //SWITCH_CPU_ACCESS_LEVEL(privileged); ***************if you put it there when make EXTI configration the
    //program will make HardFault_Handler becouse in configration you write NVIC in cpu put you donont have
    //Access to write on it ******************************************************************************

	EXTI_CONGIG.exti_conf = EXTI9PB9;
	EXTI_CONGIG.trigger_case = EXTI_Trigger_Falling;
	EXTI_CONGIG.IRQ_EN = EXTI_IRQ_Enable;
	EXTI_CONGIG.P_IRQ_call_back = INT_ACTION;
	MCAL_EXTI_GPIO_INIT(&EXTI_CONGIG);
	//SWITCH_CPU_ACCESS_LEVEL(unprivileged);

	main_os();
	while(1){

		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else
		{

		}


	}
}
