/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Learn-in-depth
//Ma7moud3id
//Mastering_Embedded System online diploma
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE    0x40010800
#define GPIOA_CRH     *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL     *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR     *(volatile uint32_t *)(GPIOA_BASE + 0x0C)




//Clock
#define RCC_BASE      0x40021000
#define RCC_APB2ENR   *(volatile uint32_t *)(RCC_BASE + 0x18)
//interrupt
#define EXTI_BASE      0x40010400
#define EXTI_IMR   *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR   *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR   *(volatile uint32_t *)(EXTI_BASE + 0x14)
//AFIO
#define AFIO      0x40010000
#define AFIO_EXTICR1   *(volatile uint32_t *)(AFIO + 0x08)
//NVIC
#define NVIC_ISER0   *(volatile uint32_t *)(0xE000E100)

void init_AFIO(void){

    AFIO_EXTICR1 |= 0b0000<<0;
}
void clock (void){
	//clock_GPIO
	RCC_APB2ENR |= 1<<2;
	//clock_AFIO
	RCC_APB2ENR |=1<<0;
}
void init_GPIO(void){

	//register_GPIO
	GPIOA_CRH &= 0xFF0FFFFF;
    GPIOA_CRH |= 0x00200000;
    GPIOA_CRL |= 0b01<<2;
}
void init_intrrupt (void){
	//masked
	EXTI_IMR |= (1<<0) ;
	//Raised
	EXTI_RTSR |= (1<<0);
	//panding
	EXTI_PR |= (0<<0);
}
void NVIC (void){
	//NVIC
	NVIC_ISER0 |= (1<<6);
}
void Toggel(unsigned char Pin){
	GPIOA_ODR ^= 1<<Pin ;
}
int main(void)
{
	clock();
	init_GPIO();
	init_AFIO();
	init_intrrupt();
	NVIC();
    while(1);
   /* {

       for (int i = 0; i < 5000; i++); // arbitrary delay
       GPIOA_ODR &= ~(1<<13) ;
       for (int i = 0; i < 5000; i++); // arbitrary delay
    }*/
}
void EXTI0_IRQHandler (void){
	Toggel(13);
	EXTI_PR |= (1<<0);
}
