/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Learn-in-depth
//Ma7moud3id
//Mastering_Embedded System online diploma
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address GPIOA
#define GPIOA_BASE    0x40010800
#define GPIOA_CRH     *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL     *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR     *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR     *(volatile uint32_t *)(GPIOA_BASE + 0x08)

// register address GPIOB
#define GPIOB_BASE    0x40010C00
#define GPIOB_CRH     *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL     *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR     *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR     *(volatile uint32_t *)(GPIOB_BASE + 0x08h)


//Clock
#define RCC_BASE      0x40021000
#define RCC_APB2ENR   *(volatile uint32_t *)(RCC_BASE + 0x18)


void clock (void){
	//clock_GPIO
	//GPIOA
	RCC_APB2ENR |= 1<<2;
	//GPIOB
	RCC_APB2ENR |= 1<<3;

}
void init_GPIO(void){

	//register_GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
    GPIOA_CRH |= 0b0100<<20;
    GPIOA_CRL |= 0b0100<<4;
    //register_GPIOB
    GPIOB_CRH &= 0xFF0FFFFF;
    GPIOB_CRH |= 0b0001<<20;
    GPIOB_CRL |= 0b0001<<4;


}
void wait_ms(uint32_t time){
	uint32_t i,j;

	for(i=0;i<time;i++){
		for(j=0;j<255;j++);
	}
}
int main(void)
{
	clock();
	init_GPIO();
	//GPIOB_ODR &=0xFF0FFFF0;
	GPIOB_ODR &= ~( 1<<1);
	//GPIOB_ODR &=0xFF0FFFFF;
	GPIOB_ODR &= ~( 1<<13);
	while(1){
		if((GPIOA_IDR >>1 & 1)){//single click
			GPIOB_ODR |= ( 1<<13);
			GPIOB_ODR ^= (1<<1);
			while(!(GPIOA_IDR >>1 & 1));
		}
		if(GPIOA_IDR >>13 & 1){//multi click
			GPIOB_ODR ^= (1<<13);
		}
		//wait_ms(1);

	}
}
