/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC 0x40021000
#define GPIO 0x40010800
#define RCC_APB2ENT (*(unsigned int *)(RCC+0x18))
#define GPIO_CRH (*(unsigned int *)(GPIO+0x04))
#define GPIO_ODR (*(unsigned int *)(GPIO+0x0C))
typedef volatile unsigned int vuint32_t;
typedef union{
	vuint32_t all_port;
	struct{
		unsigned reseved :13;
		unsigned pin_13 :1;

	}pin;
}pins;
volatile pins* pr =(volatile pins*) (GPIO+0x0C);
int main(void)
{
	RCC_APB2ENT|=(1<<2);
	GPIO_CRH &= 0xFF0FFFFF;
	GPIO_CRH |= 0x00200000;

    /* Loop forever */
	for(;;){
		pr->pin.pin_13=1;
		int i;
		for( i =0; i<5000;i++);
		pr->pin.pin_13=0;
		for( i =0; i<5000;i++);
	}
}
